data = {
    'Федеральный портал проектов НПА (уровень Правительства РФ)': 'https://regulation.gov.ru/',
    'Государственная Дума': 'https://sozd.duma.gov.ru/', 
    'Центральный Банк': 'https://cbr.ru/project_na/', 
    'Евразийская экономическая комиссия': 'https://eec.eaeunion.org/',
    'Свердловская область': 'http://regulation.midural.ru/', 
    'Республика Адыгея': 'https://regulation.adygeya.ru/', 
    'Республика Башкортостан': 'https://regulation.bashkortostan.ru/ ', 
    'Республика Бурятия': 'https://egov-buryatia.ru/minec/activities/zaklyucheniya-ob-otsenke-reguliruyushchego-vozdeystviya-2017.php?clear_cache=Y', 
    'Республика Алтай': 'https://orv.mineco04.ru/projects#', 
    'Республика Тыва': 'http://mert.tuva.ru', 
    'Республика Хакасия': 'https://orv.r-19.ru/rl/', 
    'Алтайский край': 'https://altairegion22.ru/gov/pravitelstvo-altayskogo-kraya/administration/stuct/economy/otsenka-reguliruyushchego-vozdeystviya/normativnye-dokumenty-orv/normativnye-dokumenty-altayskogo-kraya/', 
    'Республика Дагестан': 'http://dagorv.ru/projects#', 
    'Республика Ингушетия': 'https://npa.ingushetia.ru/projects', 
    'Кабардино-Балкарская Республика': 'http://regulation.economykbr.ru/projects', 
    'Республика Калмыкия': 'https://economy.kalmregion.ru/deyatelnost/orv/', 
    'Карачаево-Черкесская Республика': ['https://economykchr.ru/opot', 'https://economykchr.ru/otsenka-reguliruyushchego-vozdejstviya'], 
    'Чувашская Республика - Чувашия': 'https://nk.cap.ru/projects', 
    'Республика Коми': 'https://econom.rkomi.ru/activity/539/', 
    'Республика Карелия': 'https://orv.economy.gov10.ru/', 
    'Хабаровский край': 'https://regulation.khv.gov.ru/projects', 
    'Чеченская республика': 'https://economy-chr.ru/otsenka-reguliruyushchego-vozdejstviya/zaklyucheniya-ob-orv', 
    'Краснодарский край': ['https://regulation.krasnodar.ru', 'https://dirmsp.krasnodar.ru/activity/orv'], 
    'Республика Татарстан (Татарстан)': 'https://mert.tatarstan.ru/publichnie-konsultatsii.htm', 
    'Удмуртская Республика': 'https://regulation.udmr.ru', 
    'Красноярский край': 'http://www.krskstate.ru/zakonprojekts/documents?doctype=0&priem_person=0&docs_proc=3&keywords=&searchphrase=exact', 
    'Приморский край': 'https://regulation-new.primorsky.ru/', 
    'Ставропольский край': 'https://stavinvest.ru/work/evaluation-of-regulatory-impact-in-stavropol-territory/', 
    'Амурская область': 'https://or28.amurobl.ru/otsenka-reguliruyushchego-vozdeystviya-or/otsenka-reguliruyushchego-vozdeystviya-proektov-aktov-amurskoy-oblasti/', 
    'г. Москва': 'https://www.mos.ru/depr/function/orv-ofv/orv-ofv-rezultaty/rezultaty-v-tekushem-godu/', 
    'Астраханская область': 'https://minec.astrobl.ru/directions/ocenka-reguliruyuschego-vozdeystviya-za-2024-god', 
    'Белгородская область': 'https://belgorodinvest.com/docs/otsenka-reguliruyushchego-vozdeystviya/', 
    'Брянская область': 'https://econom32.ru/activity/ocenka/zakon/', 
    'Владимирская область': 'https://regulation.avo.ru/', 
    'Волгоградская область': 'https://niktokromenas.volgograd.ru/orv/regional/discussions', 
    'Вологодская область': 'http://pravo.gov35.ru/', 
    'Воронежская область': 'http://npa.govvrn.ru/', 
    'Ивановская область': 'https://derit.ivanovoobl.ru/deyatelnost/otsenka-reguliruyushchego-vozdeystviya/otsenka-reguliruyushchego-vozdeystviya-proektov-npa/proekty-npa/', 
    'Иркутская область': 'https://regulation.irkobl.ru; https://irkobl.ru/sites/economy/orv/', 
    'Калининградская область': 'https://regulation.gov39.ru/', 
    'Калужская область': ['https://minek.admoblkaluga.ru/page/orv/', 'http://admoblkaluga.ru/sub/evaluationNPA'], 
    'Камчатский край': ['https://www.kamgov.ru/minecon/ocenka-reguliruusego-vozdejstvia/publicnye-konsultacii-po-proektam-npa-kamcatskogo-kraa-v-ramkah-ocenki-reguliruusego-vozdejstvia', 'http://regulation.kamgov.ru/'], 
    'Кемеровская область - Кузбасс': 'https://regulation.kemobl.ru/', 
    'Кировская область': 'http://regulation.kirov.ru/', 
    'Костромская область': 'https://regulation.kostroma.gov.ru/docs/index.aspx?kind=1', 
    'Курганская область': 'https://orv45.ru/', 
    'Курская область': 'https://xn--j1aarei.xn--p1ai/region/economy/otsenka-reguliruyushchego-vozdeystviya-i-ekspertiza/', 
    'Ленинградская область': 'http://regulation.lenreg.ru/ ', 
    'Липецкая область': 'https://regulation.lipetsk.gov.ru', 
    'Магаданская область': 'https://economy.49gov.ru/activities/appraisal/decisions/', 
    'Московская область': 'https://regulation.mosreg.ru/projects', 
    'Мурманская область': 'https://openregion.gov-murman.ru/acts/', 
    'Нижегородская область': 'https://nobl.ru/deyatelnost-pravitelstva/orv/', 
    'Новгородская область': 'https://regulation.novreg.ru/projects', 
    'Новосибирская область': 'https://dem.nso.ru/npa/bills', 
    'Омская область': 'https://regulation.omskportal.ru/Regulation/Materials', 
    'Оренбургская область': 'https://regulation.orb.ru/', 
    'Орловская область': 'http://regulation.orel-region.ru', 
    'Пензенская область': 'https://merp.pnzreg.ru/gosupravlenie/kontrolno-nadzornaya-deyatelnost/orv/zaklyucheniya-ob-orv/', 
    'Пермский край': 'https://economy.permkrai.ru/otsenka-reguliruyushchego-vozdeystviya/publichnye-obsuzhdeniya-proektov-npa', 
    'Псковская область': 'https://regulation.pskov.ru/projects', 
    'Ростовская область': 'https://www.donland.ru/npa-expertise/?filter_disscuss=archive&nav-news=page-1', 
    'Рязанская область': 'https://mineconom.ryazan.gov.ru/direction/otsenka_reguliruyushchego_vozdeystviya/zaklyucheniya_i_materialy_ob_otsenke_reguliruyushchego_vozdeystviya/', 
    'Самарская область': 'https://regulation.samregion.ru/projects', 
    'Саратовская область': 'https://saratov.gov.ru/law/impact/zakl-impact/', 
    'Сахалинская область': 'https://orv.sakhalin.gov.ru/projects', 
    'Смоленская область': 'https://regulation.admin-smolensk.ru/projects', 
    'Тамбовская область': 'https://regulation.tambov.gov.ru/', 
    'Тверская область': 'http://orv.tver.ru/', 
    'Томская область': 'http://orv-tomsk.ru/publichnye_konsultacii/', 
    'Тульская область': 'https://regulation.tularegion.ru/#', 
    'г. Санкт-Петербург': 'http://regulation.cipit.gov.spb.ru', 
    'Ульяновская область': 'http://73.regportal.pba.su/Regulation/Information/6', 
    'Челябинская область': 'regulation.ulgov.ru', 
    'Забайкальский край': 'https://minek.75.ru/deyatel-nost/ocenka-reguliruyuschego-vozdeystviya/ocenka-proektov/zaklyucheniya-ob-ocenke-reguliruyuschego-vozdeystviya-na-proekty-normativnyh-pravovyh-aktov', 
    'Ханты-Мансийский автономный округ - Югра': 'https://depeconom.admhmao.ru/deyatelnost/otsenka-reguliruyushchego-vozdeystviya/', 
    'Тюменская область': 'http://regulation.tyumen.gov.ru/regulations/EX/orv.htm', 
    'Ямало-Ненецкий автономный округ': 'https://orv.yanao.ru/projects', 
    'Еврейская автономная область': 'https://eao.ru/isp-vlast/departament-ekonomiki-pravitelstva-evreyskoy-avtonomnoy-oblasti/otsenka-reguliruyushchego-vozdeystviya/', 
    'Архангельская область': 'https://regulation.dvinaland.ru/docs/regulation/', 
    'Ненецкий автономный округ': 'https://regulation.adm-nao.ru/', 
    'Чукотский автономный округ': 'https://dep.invest-chukotka.ru/orv', 
    'Ярославская область': 'https://portal.yarregion.ru/depts-usp/activity/orv/otsenka-reguliruyushchego-vozdeystviya-/',
    'Республика Крым': 'https://minek.rk.gov.ru/structure/4829360c-eb16-4e0e-b884-66647208e947',
    'г. Севастополь': 'https://sev.gov.ru/docs/326/',
    'Республика Саха - Якутия': 'https://xn--14-9kcqjffxnf3b.xn--p1ai/orv/',
    'Республика Марий Эл': 'https://mari-el.gov.ru/ministries/mecon/pages/ozenka-reg-vozdeystvija/#close',
    'Республика Северная Осетия-Алания': 'https://economyrso.ru/publichnye-obsuzhdeniya.html',
    'Республика Мордовия': 'https://mineco.e-mordovia.ru/directions-of-activity/regulatory-impact/opinions-on-ods/index.php'
}